#pragma once
#include <iostream>
#include <cstdio>
#include <string>
#include <vector>
#include <cctype>
#include <ctime>
#include <stdexcept>
#include <climits>
#include <locale>
#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <random>
#include <mpir.h>